name: Build Superman Full

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project
        shell: powershell
        run: |
          Expand-Archive -Path "Superman-project.zip" -DestinationPath "project" -Force

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64

      - name: Build ASI
        shell: cmd
        run: |
          cd project
          msbuild Superman.vcxproj /p:Configuration=Release /p:Platform=x64 /m

      - name: Check output
        shell: powershell
        run: |
          Get-ChildItem -Path project -Recurse -Filter "Superman.asi"

      - name: Upload Superman.asi
        uses: actions/upload-artifact@v4
        with:
          name: Superman-FULL-GTA5-Legacy-3889
          path: project\**\Superman.asi
          if-no-files-found: error
